import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mainnav}>
        <ul>
          <Link href='/'><li>Home</li></Link>
          <Link href='/about'><li>About</li></Link>
          <Link href='/blog'><li>Blogs</li></Link>
          <Link href='/contact'><li>Contact</li></Link>
        </ul>
      </nav>
      <main className={`${styles.main} ${inter.className}`}>
        <div><h1 className={styles.title}>
          Hunting Coder
        </h1></div>

        <div>

        <p className={styles.description}>
          A blog for coders by a coder
        </p></div>

        <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          <div className={styles.blogitems}>
            <h3>How to learn JS in 2023</h3>
            <p>Lorem ipsum dolor sit amet consectetur.</p>
          </div>
          <div className={styles.blogitems}>
            <h3>How to learn C++ in 2023</h3>
            <p>Lorem ipsum dolor sit amet consectetur.</p>
          </div>
          <div className={styles.blogitems}>
            <h3>How to learn Python in 2023</h3>
            <p>Lorem ipsum dolor sit amet consectetur.</p>
          </div>

        </div>

        
      </main>
    </>
  )
}
