import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Script from 'next/script'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous"></link>
      </Head>

      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous" />      

      

      
      <main className={`${styles.main} ${inter.className}`}>
        <div><h1 className={styles.title}>
          Hunting Coder
        </h1></div>

        <div>

        <p className={styles.description}>
          A blog for coders by a coder
        </p></div>

        <div className={styles.blogs}>
          <h2>Popular Blogs</h2>
          <div className={styles.blogitems}>
            <h3>How to learn JS in 2023</h3>
            <p>Lorem ipsum dolor sit amet consectetur.</p>
          </div>
          <div className={styles.blogitems}>
            <h3>How to learn C++ in 2023</h3>
            <p>Lorem ipsum dolor sit amet consectetur.</p>
          </div>
          <div className={styles.blogitems}>
            <h3>How to learn Python in 2023</h3>
            <p>Lorem ipsum dolor sit amet consectetur.</p>
          </div>

        </div>

        

        

        
      </main>
      
    </>
  )
}
